name: Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean previous build
        run: |
          rm -rf _build

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html source _build/html

      - name: DEBUG: Check what was built
        run: |
          echo "=== FULL BUILD DIRECTORY LISTING ==="
          ls -la _build/html/
          echo ""
          echo "=== FIRST 10 LINES OF index.html ==="
          head -10 _build/html/index.html
          echo ""
          echo "=== FILE SIZES ==="
          du -sh _build/html/* | head -10
          echo ""
          echo "=== CHECK IF INDEX.HTML HAS CONTENT ==="
          if [ -s "_build/html/index.html" ]; then
            echo "✅ index.html exists and has content"
            echo "File size: $(wc -c < _build/html/index.html) bytes"
          else
            echo "❌ index.html is empty or missing"
          fi

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
